CXX = g++
CXXFLAGS = -std=c++17 -Wall

main:
	$(CXX) $(CXXFLAGS) Esercizio1_3.cpp ../../Simulation.cpp ../../functions.cpp ../../../Parallel\ Random\ Number\ Generator-20260727/random.cpp -o main

clean:
	rm -f main